name: Test

on:
  - push
  - pull_request

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"  
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Tests
        run: |
          bundle install
          bundle exec rake test
          bundle exec rake build
          gem install pkg/rdtool-*.gem
# MRI:
#   name: ${{ matrix.os }} ruby-${{ matrix.ruby }}
#   runs-on: ${{ matrix.os }}
#   strategy:
#     fail-fast: false
#     matrix:
#       os: [ubuntu-latest, macos-11, windows-2022]
#       ruby: [ '3.1', '3.2,', '3.3', '3.4', head]
#       include:
#         - { os: windows-2022 , ruby: mswin }
#   steps:
#     - uses: actions/checkout@v2
#     - name: Set up Ruby ${{ matrix.ruby }}
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: ${{ matrix.ruby }}
#     - name: Build and Install
#       run: |
#         gem install --no-document bundler
#         gem build numru-narray.gemspec
#         gem install numru-narray-*.gem
#         bundle install
#     - name: Tests
#       run: rake test
#   ruby-head-debug:
#     name: Build on ruby-head-debug
#     runs-on: ubuntu-latest
#     continue-on-error: true
#     strategy:
#       fail-fast: false
#       matrix:
#         ruby: [ 'debug' ]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Ruby ${{ matrix.ruby }}
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: ${{ matrix.ruby }}
#       - name: Build and Install
#         run: |
#           gem install --no-document bundler
#           gem build numru-narray.gemspec
#           gem install numru-narray-*.gem
#           bundle install
#       - name: Tests
#         run: rake test
